<?php

namespace App\Facades;

use Illuminate\Support\Facades\Facade;

class SuffixService extends Facade
{
 protected static function getFacadeAccessor()
 {
     return 'Suffix';
//     parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
 }
}